/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import controller.Ordenacao;
import controller.Utilidades;
import java.util.ArrayList;
import model.ModelLista;
/**
 *
 * @author laboratorio
 */
public class JFramePrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFramePrincipal.class.getName());

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
        jPanelResultados.setVisible(false);
        ModelLista.lista = new ArrayList<>();
    }

    ArrayList<Float> metricas = new ArrayList<>();
    long tempoInicio, tempoFim;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAbrir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        txtNomeArquivo = new javax.swing.JTextField();
        lblCaminho = new javax.swing.JLabel();
        lblMetodos = new javax.swing.JLabel();
        cbmBoxMetodos = new javax.swing.JComboBox<>();
        jPanelResultados = new javax.swing.JPanel();
        txtQtdNumeros = new javax.swing.JTextField();
        lblQtdNumeros = new javax.swing.JLabel();
        txtTrocas = new javax.swing.JTextField();
        lblTrocas = new javax.swing.JLabel();
        lblTempo = new javax.swing.JLabel();
        txtTempo = new javax.swing.JTextField();
        lblComparacoes = new javax.swing.JLabel();
        txtComparacoes = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        btnExecutar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesquisa e Ordenação");

        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(this::btnAbrirActionPerformed);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        lblCaminho.setText("Digite aqui o nome do arquivo e caminho:");

        lblMetodos.setText("Métodos de Ordenação");

        cbmBoxMetodos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bolha", "Seleção", "Inserção", "Pente" }));

        txtQtdNumeros.setEditable(false);
        txtQtdNumeros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtQtdNumeros.setEnabled(false);
        txtQtdNumeros.setFocusable(false);

        lblQtdNumeros.setText("Quantidade de Números: ");

        txtTrocas.setEditable(false);
        txtTrocas.setEnabled(false);

        lblTrocas.setText("Quantidade de Trocas: ");

        lblTempo.setText("Tempo(ms):");

        txtTempo.setEditable(false);
        txtTempo.setEnabled(false);

        lblComparacoes.setText("Quantidade de Comparações: ");

        txtComparacoes.setEditable(false);
        txtComparacoes.setEnabled(false);

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Métodos", "Comparações", "Trocas", "Tempo(ms)"
            }
        ));
        jScrollPane2.setViewportView(tblResultados);

        javax.swing.GroupLayout jPanelResultadosLayout = new javax.swing.GroupLayout(jPanelResultados);
        jPanelResultados.setLayout(jPanelResultadosLayout);
        jPanelResultadosLayout.setHorizontalGroup(
            jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelResultadosLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultadosLayout.createSequentialGroup()
                        .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTrocas)
                            .addComponent(lblTempo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTempo, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                            .addComponent(txtTrocas)))
                    .addGroup(jPanelResultadosLayout.createSequentialGroup()
                        .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQtdNumeros)
                            .addComponent(lblComparacoes))
                        .addGap(12, 12, 12)
                        .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtComparacoes)
                            .addComponent(txtQtdNumeros)))))
        );
        jPanelResultadosLayout.setVerticalGroup(
            jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTrocas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTrocas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTempo)
                    .addComponent(txtTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComparacoes)
                    .addComponent(txtComparacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtdNumeros)
                    .addComponent(txtQtdNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExecutar.setText("Executar");
        btnExecutar.addActionListener(this::btnExecutarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMetodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbmBoxMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExecutar, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(txtNomeArquivo)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCaminho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbrir)
                    .addComponent(btnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMetodos)
                    .addComponent(cbmBoxMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(btnExecutar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtNomeArquivo.setText(" ");
        ModelLista.lista.clear();
        cbmBoxMetodos.setSelectedIndex(0);
        txtComparacoes.setText("");
        txtTrocas.setText("");
        txtTempo.setText("");
        txtNomeArquivo.requestFocusInWindow();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnExecutarActionPerformed(java.awt.event.ActionEvent evt) {
if( ModelLista.lista.isEmpty()){
            JOptionPane.showMessageDialog(this, "O arquivo não foi carregado para a lista", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            jPanelResultados.setVisible(true); 
            switch (cbmBoxMetodos.getSelectedIndex()){
                case 0: // bolha
                    metricas.clear();
                    tempoInicio = System.nanoTime();
                    metricas.addAll(controller.Ordenacao.bolha(ModelLista.lista));
                    tempoFim = System.nanoTime(); 
                    metricas.add((float)(tempoFim - tempoInicio ) / 1000000); 
                    break;
                case 1: // insercao
                    metricas.clear();
                    tempoInicio = System.nanoTime();
                    metricas.addAll(controller.Ordenacao.insercao(ModelLista.lista));
                    tempoFim = System.nanoTime(); 
                    metricas.add((float)(tempoFim - tempoInicio ) / 1000000);          
                    break;
                case 2: // pente
                    metricas.clear();
                    tempoInicio = System.nanoTime();
                    metricas.addAll(controller.Ordenacao.pente(ModelLista.lista));
                    tempoFim = System.nanoTime(); 
                    metricas.add((float)(tempoFim - tempoInicio ) / 1000000);
                    break;
                    
                case 3: //selecao
                    metricas.clear();
                    tempoInicio = System.nanoTime();
                    metricas.addAll(controller.Ordenacao.selecao(ModelLista.lista));
                    tempoFim = System.nanoTime(); 
                    metricas.add((float)(tempoFim - tempoInicio ) / 1000000);
                    break;
                    
                default:
                    throw new AssertionError(); 
            }
        }  
        
            txtQtdNumeros.setText(""+ModelLista.lista.size()); 
            txtComparacoes.setText(""+metricas.get(0));
            txtTrocas.setText(""+metricas.get(1));
            txtTempo.setText(""+metricas.get(2));
           
        
        //jPanel1Resultados.setVisible(true);
        //System.out.println(CmbMetodo.getSelectedIndex() + " " + CmbMetodo.getSelectedItem());        
    }


    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {
    if(txtNomeArquivo.getText().equals("")){        
        JOptionPane.showMessageDialog(this, "Informe o nome do arquivo", "Atenção", JOptionPane.ERROR_MESSAGE);
    } else { 
       if( Utilidades.carregarArquivoList(txtNomeArquivo.getText(), ModelLista.lista)) {
           JOptionPane.showMessageDialog(this, "Lista carregada com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
       } else {
           JOptionPane.showMessageDialog(this, "Problemas para ler o arquivo e carregar a lista", "Erro",
                   JOptionPane.ERROR_MESSAGE);
           txtTempo.setText("");
           txtNomeArquivo.requestFocusInWindow();
       }
    }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFramePrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnExecutar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cbmBoxMetodos;
    private javax.swing.JPanel jPanelResultados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCaminho;
    private javax.swing.JLabel lblComparacoes;
    private javax.swing.JLabel lblMetodos;
    private javax.swing.JLabel lblQtdNumeros;
    private javax.swing.JLabel lblTempo;
    private javax.swing.JLabel lblTrocas;
    private javax.swing.JTable tblResultados;
    private javax.swing.JTextField txtComparacoes;
    private javax.swing.JTextField txtNomeArquivo;
    private javax.swing.JTextField txtQtdNumeros;
    private javax.swing.JTextField txtTempo;
    private javax.swing.JTextField txtTrocas;
    // End of variables declaration//GEN-END:variables
}
